# Generated by Django 4.1.7 on 2023-05-03 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('costs', '0002_remove_cost_category_cost_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='category',
        ),
        migrations.AlterField(
            model_name='cost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cost_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cost',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_cost', to='costs.categorycost', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
