# Generated by Django 4.1.7 on 2023-05-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0003_remove_cost_category_alter_cost_user_cost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycost',
            name='day_sum',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Сумма'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cost',
            name='cost_sum',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
    ]
