# Generated by Django 4.1.7 on 2023-05-04 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('costs', '0004_daycost_day_sum_alter_cost_cost_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cost_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
