# Generated by Django 4.1.7 on 2023-05-04 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('costs', '0005_alter_cost_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daycost',
            name='day_sum',
        ),
        migrations.AlterField(
            model_name='cost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cost_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
