# Generated by Django 4.1.7 on 2023-06-24 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('costs', '0006_remove_daycost_day_sum_alter_cost_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[], max_length=1000, verbose_name='Категория')),
                ('addcash_date', models.DateField(verbose_name='День')),
                ('addcash_name', models.CharField(blank=True, max_length=1000, verbose_name='Инфо')),
                ('addcash_sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='addmoney_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Приход',
                'verbose_name_plural': 'Приходы',
            },
        ),
    ]
