# Generated by Django 4.1.7 on 2023-06-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0008_rename_addcash_date_addmoney_addmoney_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAddMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Категория поступлений',
                'verbose_name_plural': 'Категории поступлений',
            },
        ),
        migrations.AlterField(
            model_name='addmoney',
            name='category',
            field=models.CharField(blank=True, choices=[('Карточный перевод', 'Карточный перевод'), ('Наличные', 'Наличные')], max_length=1000, verbose_name='Категория'),
        ),
    ]
