# Generated by Django 4.1.7 on 2023-06-25 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0009_categoryaddmoney_alter_addmoney_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmoney',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_addmoney', to='costs.categoryaddmoney', verbose_name='Категория'),
        ),
    ]
