# Generated by Django 4.1.7 on 2023-06-25 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0010_alter_addmoney_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addmoney',
            options={'verbose_name': 'Поступление', 'verbose_name_plural': 'Поступления'},
        ),
    ]
