# Generated by Django 4.1.7 on 2023-04-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('IT', 'IT'), ('Дом', 'Дом'), ('Досуг', 'Досуг'), ('Покупки', 'Покупки'), ('Приготовление еды', 'Приготовление еды')], max_length=30, null=True, verbose_name='Категория'),
        ),
    ]
