# Generated by Django 4.1.7 on 2023-04-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_categorytask_delete_category_alter_task_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytask',
            name='user',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
