# Generated by Django 4.1.7 on 2023-05-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='admin', max_length=100)),
                ('day_date', models.DateField(verbose_name='День')),
                ('day_cost', models.CharField(blank=True, max_length=20000)),
            ],
            options={
                'verbose_name': 'Дневной расход',
                'verbose_name_plural': 'Дневные расходы',
            },
        ),
    ]
