# Generated by Django 4.1.7 on 2023-05-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_daycost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DayCost',
        ),
    ]
