# Generated by Django 4.1.7 on 2023-06-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_delete_daycost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=2500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=2500, verbose_name='Примечания'),
        ),
    ]
